name: Go

on:
  push:
    branches:
      - "develop"
      - "feature/cicd"
  pull_request:
    branches:
      - "develop"

env:
  REGISTRY_URL: thainm
  IMAGE_NAME: uet-class-backend
  BRANCH_NAME: develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.io --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME-latest .
          docker tag ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME-latest ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME-$GITHUB_SHA

      - name: Push the built image to Docker Hub
        run: |
          docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME-latest
          docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$BRANCH_NAME-$GITHUB_SHA

  deploy:
    # needs: build
    runs-on: ubuntu-20.04
    container: google/cloud-sdk
    steps:
      - name: Check status
        run: ls -la

      - name: Check gcloud SDK status
        run: gcloud version

      - name: Authenticate with Google Cloud Platform
        run: |
          echo "${{ secrets.GA_GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > github-actions-sa.json
          cat github-actions-sa.json
          gcloud auth activate-service-account ${{ secrets.GA_GCP_SERVICE_ACCOUNT_EMAIL }} --key-file=github-actions-sa.json --project=${{ secrets.GA_GCP_PROJECT_ID }}

      - name: SSH to the remote server and pull new images
        run: |
          gcloud compute ssh ${{ secrets.GCP_DEVELOP_SERVER_HOST }} --zone=${{ secrets.GCP_PROJECT_ZONE }} --command="ls -la"
